#!/usr/bin/env python3
""" This will publish coordinates for a circle

Publishers:
  point (geometry_msgs/Point) - circle coordinates

  ETC... 
"""
import rospy

def main():
    rospy.init_node("circle_node")
    rospy.logerror("hello")

if __name__ == "__main__":
    main()