#!/usr/bin/env python3
""" This will publish coordinates for a circle

Publishers:
  point (geometry_msgs/Point) - circle coordinates

  ETC... 
"""
import rospy
from math import cos, sin, pi
from geometry_msgs.msg import Point

class Circle:
    def __init__(self, radius):
        """ a circle with a given radius
            Args:
                radius (float) - the radius of the circle
        """
        self._radius = radius

    def xy(self, t):
        """ a circle parameterized by time
            Args:
                t (float): time in seconds
            Return:
                tuple (x,y) coordinates of the circle at the given time
        """
        return (self._radius * cos(2*pi*t/100), self._radius *sin(2*pi*t/100))

def main():
    point_pub = rospy.Publisher("point", Point, queue_size=10)
    rospy.init_node("circle_node")
    r = rospy.Rate(10)
    t = 0
    circ = Circle(2)
    while not rospy.is_shutdown():
        x, y = circ.xy(t)
        point_pub.publish(Point(x, y, 1))
        rospy.loginfo(f"hello {t} {x} {y} ")
        t += 1
        r.sleep()

if __name__ == "__main__":
    main()